// Curated template presets for Maker's Market storefront builder
import type { StorefrontSection } from './builder-sections'

export interface BuilderTemplate {
  id: string
  name: string
  description: string
  vibe: string
  emoji: string
  colors: {
    primary: string
    secondary: string
    accent: string
    background: string
    surface: string
    text: string
    textMuted: string
    heading: string
    border: string
  }
  fonts: { heading: string; body: string }
  cardStyle: { variant: 'white' | 'tinted' | 'glass'; border: string; iconStyle: string }
  heroSettings: { style: 'image' | 'gradient'; height: string; overlayOpacity: number }
  sections: StorefrontSection[]
  gradients: { hero: string; accent: string; card: string }
}

export const BUILDER_TEMPLATES: BuilderTemplate[] = [
  {
    id: 'classic-bakery',
    name: 'Classic Bakery',
    description: 'Warm, traditional, timeless',
    vibe: 'Like a cozy neighborhood bakery',
    emoji: '🍞',
    colors: {
      primary: '#8B5E3C',
      secondary: '#D4A574',
      accent: '#C67B3C',
      background: '#FFF8F0',
      surface: '#FFFFFF',
      text: '#3D2B1F',
      textMuted: '#8B7355',
      heading: '#5C3D2E',
      border: '#E8D5C4',
    },
    fonts: { heading: 'Playfair Display', body: 'Lora' },
    cardStyle: { variant: 'white', border: 'none', iconStyle: 'solid' },
    heroSettings: { style: 'image', height: 'medium', overlayOpacity: 0.3 },
    gradients: {
      hero: 'linear-gradient(135deg, #8B5E3C 0%, #D4A574 100%)',
      accent: 'linear-gradient(135deg, #C67B3C 0%, #D4A574 100%)',
      card: 'linear-gradient(135deg, #FFF8F0 0%, #F5E6D3 100%)',
    },
    sections: [
      { id: 'tpl-hero', sectionType: 'hero', config: { height: 'large', showTagline: true, showCTA: true }, isVisible: true },
      { id: 'tpl-featured', sectionType: 'featured_products', config: { count: 3, style: 'card' }, isVisible: true },
      { id: 'tpl-about', sectionType: 'about_me', config: { style: 'card' }, isVisible: true },
      { id: 'tpl-products', sectionType: 'all_products', config: { layout: 'grid', showFilters: true }, isVisible: true },
      { id: 'tpl-reviews', sectionType: 'reviews', config: { count: 3, style: 'carousel' }, isVisible: true },
      { id: 'tpl-pickup', sectionType: 'pickup_details', config: { showMap: false }, isVisible: true },
      { id: 'tpl-hours', sectionType: 'shop_hours', config: {}, isVisible: true },
    ],
  },
  {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    description: 'Clean, sharp, contemporary',
    vibe: 'Sleek and sophisticated',
    emoji: '✨',
    colors: {
      primary: '#1A1A1A',
      secondary: '#555555',
      accent: '#FF6B35',
      background: '#FFFFFF',
      surface: '#FAFAFA',
      text: '#1A1A1A',
      textMuted: '#888888',
      heading: '#000000',
      border: '#EEEEEE',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    cardStyle: { variant: 'white', border: 'primary', iconStyle: 'outline' },
    heroSettings: { style: 'gradient', height: 'small', overlayOpacity: 0 },
    gradients: {
      hero: 'linear-gradient(135deg, #1A1A1A 0%, #333333 100%)',
      accent: 'linear-gradient(135deg, #FF6B35 0%, #FF8F65 100%)',
      card: 'linear-gradient(135deg, #FAFAFA 0%, #F5F5F5 100%)',
    },
    sections: [
      { id: 'tpl-hero', sectionType: 'hero', config: { height: 'small', showTagline: true, showCTA: true }, isVisible: true },
      { id: 'tpl-products', sectionType: 'all_products', config: { layout: 'grid', showFilters: true }, isVisible: true },
      { id: 'tpl-about', sectionType: 'about_me', config: { style: 'card' }, isVisible: true },
      { id: 'tpl-pickup', sectionType: 'pickup_details', config: { showMap: false }, isVisible: true },
    ],
  },
  {
    id: 'rustic-farmhouse',
    name: 'Rustic Farmhouse',
    description: 'Earthy, warm, handcrafted',
    vibe: 'Fresh from the farm stand',
    emoji: '🌾',
    colors: {
      primary: '#4E6E52',
      secondary: '#8B7355',
      accent: '#C4823D',
      background: '#F5F0E8',
      surface: '#FFFDF8',
      text: '#2D3B2E',
      textMuted: '#6B7C6D',
      heading: '#3A4F3C',
      border: '#D4CCBA',
    },
    fonts: { heading: 'Merriweather', body: 'Source Sans 3' },
    cardStyle: { variant: 'tinted', border: 'secondary', iconStyle: 'solid' },
    heroSettings: { style: 'image', height: 'large', overlayOpacity: 0.25 },
    gradients: {
      hero: 'linear-gradient(135deg, #4E6E52 0%, #7A9B7E 100%)',
      accent: 'linear-gradient(135deg, #C4823D 0%, #D4A574 100%)',
      card: 'linear-gradient(135deg, #F5F0E8 0%, #EDE5D8 100%)',
    },
    sections: [
      { id: 'tpl-hero', sectionType: 'hero', config: { height: 'large', showTagline: true, showCTA: true }, isVisible: true },
      { id: 'tpl-featured', sectionType: 'featured_products', config: { count: 4, style: 'card' }, isVisible: true },
      { id: 'tpl-about', sectionType: 'about_me', config: { style: 'card' }, isVisible: true },
      { id: 'tpl-categories', sectionType: 'product_categories', config: { showCounts: true }, isVisible: true },
      { id: 'tpl-products', sectionType: 'all_products', config: { layout: 'grid', showFilters: true }, isVisible: true },
      { id: 'tpl-reviews', sectionType: 'reviews', config: { count: 3, style: 'carousel' }, isVisible: true },
      { id: 'tpl-pickup', sectionType: 'pickup_details', config: { showMap: false }, isVisible: true },
      { id: 'tpl-hours', sectionType: 'shop_hours', config: {}, isVisible: true },
      { id: 'tpl-faq', sectionType: 'faq', config: { items: [] }, isVisible: true },
    ],
  },
  {
    id: 'bold-colorful',
    name: 'Bold & Colorful',
    description: 'Vibrant, energetic, fun',
    vibe: 'Bursting with personality',
    emoji: '🎨',
    colors: {
      primary: '#E63946',
      secondary: '#457B9D',
      accent: '#F4A261',
      background: '#FFFFFF',
      surface: '#F8F9FA',
      text: '#1D3557',
      textMuted: '#6C8EAD',
      heading: '#1D3557',
      border: '#DEE2E6',
    },
    fonts: { heading: 'Poppins', body: 'Nunito' },
    cardStyle: { variant: 'white', border: 'accent', iconStyle: 'pill' },
    heroSettings: { style: 'gradient', height: 'medium', overlayOpacity: 0 },
    gradients: {
      hero: 'linear-gradient(135deg, #E63946 0%, #F4A261 100%)',
      accent: 'linear-gradient(135deg, #457B9D 0%, #6BAED6 100%)',
      card: 'linear-gradient(135deg, #FFF5EE 0%, #FFF0E6 100%)',
    },
    sections: [
      { id: 'tpl-hero', sectionType: 'hero', config: { height: 'medium', showTagline: true, showCTA: true }, isVisible: true },
      { id: 'tpl-featured', sectionType: 'featured_products', config: { count: 4, style: 'card' }, isVisible: true },
      { id: 'tpl-categories', sectionType: 'product_categories', config: { showCounts: true }, isVisible: true },
      { id: 'tpl-products', sectionType: 'all_products', config: { layout: 'grid', showFilters: true }, isVisible: true },
      { id: 'tpl-newsletter', sectionType: 'newsletter_signup', config: { headline: 'Never miss a drop!', description: 'Be the first to know about new treats', buttonText: 'Count me in!' }, isVisible: true },
      { id: 'tpl-reviews', sectionType: 'reviews', config: { count: 3, style: 'carousel' }, isVisible: true },
      { id: 'tpl-pickup', sectionType: 'pickup_details', config: { showMap: false }, isVisible: true },
    ],
  },
  {
    id: 'elegant',
    name: 'Elegant',
    description: 'Refined, luxurious, premium',
    vibe: 'For the discerning palate',
    emoji: '🥂',
    colors: {
      primary: '#2C3E50',
      secondary: '#8E7C68',
      accent: '#C9A96E',
      background: '#FAF9F7',
      surface: '#FFFFFF',
      text: '#2C3E50',
      textMuted: '#7F8C8D',
      heading: '#1A252F',
      border: '#E0DCD4',
    },
    fonts: { heading: 'Cormorant Garamond', body: 'Raleway' },
    cardStyle: { variant: 'white', border: 'none', iconStyle: 'outline' },
    heroSettings: { style: 'image', height: 'large', overlayOpacity: 0.4 },
    gradients: {
      hero: 'linear-gradient(135deg, #2C3E50 0%, #4A6274 100%)',
      accent: 'linear-gradient(135deg, #C9A96E 0%, #D4BC8E 100%)',
      card: 'linear-gradient(135deg, #FAF9F7 0%, #F2EFEA 100%)',
    },
    sections: [
      { id: 'tpl-hero', sectionType: 'hero', config: { height: 'large', showTagline: true, showCTA: true }, isVisible: true },
      { id: 'tpl-about', sectionType: 'about_me', config: { style: 'card' }, isVisible: true },
      { id: 'tpl-featured', sectionType: 'featured_products', config: { count: 3, style: 'card' }, isVisible: true },
      { id: 'tpl-divider', sectionType: 'divider', config: { style: 'line' }, isVisible: true },
      { id: 'tpl-products', sectionType: 'all_products', config: { layout: 'grid', showFilters: true }, isVisible: true },
      { id: 'tpl-reviews', sectionType: 'reviews', config: { count: 3, style: 'carousel' }, isVisible: true },
      { id: 'tpl-pickup', sectionType: 'pickup_details', config: { showMap: false }, isVisible: true },
      { id: 'tpl-hours', sectionType: 'shop_hours', config: {}, isVisible: true },
    ],
  },
  {
    id: 'fun-playful',
    name: 'Fun & Playful',
    description: 'Bright, cheerful, friendly',
    vibe: 'Sweet treats, good vibes',
    emoji: '🧁',
    colors: {
      primary: '#FF69B4',
      secondary: '#9B59B6',
      accent: '#FFD93D',
      background: '#FFFBF5',
      surface: '#FFFFFF',
      text: '#4A3548',
      textMuted: '#9B8A99',
      heading: '#C2185B',
      border: '#F0E0F0',
    },
    fonts: { heading: 'Quicksand', body: 'Nunito' },
    cardStyle: { variant: 'glass', border: 'accent', iconStyle: 'pill' },
    heroSettings: { style: 'gradient', height: 'medium', overlayOpacity: 0 },
    gradients: {
      hero: 'linear-gradient(135deg, #FF69B4 0%, #FFD93D 100%)',
      accent: 'linear-gradient(135deg, #9B59B6 0%, #C39BD3 100%)',
      card: 'linear-gradient(135deg, #FFF0F5 0%, #FFF5EE 100%)',
    },
    sections: [
      { id: 'tpl-hero', sectionType: 'hero', config: { height: 'medium', showTagline: true, showCTA: true }, isVisible: true },
      { id: 'tpl-featured', sectionType: 'featured_products', config: { count: 4, style: 'card' }, isVisible: true },
      { id: 'tpl-products', sectionType: 'all_products', config: { layout: 'grid', showFilters: true }, isVisible: true },
      { id: 'tpl-newsletter', sectionType: 'newsletter_signup', config: { headline: 'Join the sweet life!', description: 'Get updates on new treats and special orders', buttonText: 'Yes please!' }, isVisible: true },
      { id: 'tpl-reviews', sectionType: 'reviews', config: { count: 3, style: 'carousel' }, isVisible: true },
      { id: 'tpl-about', sectionType: 'about_me', config: { style: 'card' }, isVisible: true },
      { id: 'tpl-pickup', sectionType: 'pickup_details', config: { showMap: false }, isVisible: true },
      { id: 'tpl-faq', sectionType: 'faq', config: { items: [] }, isVisible: true },
    ],
  },
  // ==========================================
  // Additional Templates (7-12)
  // ==========================================
  {
    id: 'honey-harvest',
    name: 'Honey Harvest',
    description: 'Golden, sweet, artisanal',
    vibe: 'Dripping with homemade goodness',
    emoji: '🍯',
    colors: {
      primary: '#B8860B',
      secondary: '#DAA520',
      accent: '#FF8C00',
      background: '#FFFDF5',
      surface: '#FFF9E6',
      text: '#3E2723',
      textMuted: '#8D6E63',
      heading: '#5D4037',
      border: '#F0E0B0',
    },
    fonts: { heading: 'Josefin Sans', body: 'Lato' },
    cardStyle: { variant: 'tinted', border: 'accent', iconStyle: 'solid' },
    heroSettings: { style: 'image', height: 'medium', overlayOpacity: 0.3 },
    gradients: {
      hero: 'linear-gradient(135deg, #B8860B 0%, #DAA520 50%, #FF8C00 100%)',
      accent: 'linear-gradient(135deg, #FF8C00 0%, #FFB347 100%)',
      card: 'linear-gradient(135deg, #FFFDF5 0%, #FFF3CD 100%)',
    },
    sections: [
      { id: 'tpl-hero', sectionType: 'hero', config: { height: 'medium', showTagline: true, showCTA: true }, isVisible: true },
      { id: 'tpl-featured', sectionType: 'featured_products', config: { count: 3, style: 'card' }, isVisible: true },
      { id: 'tpl-about', sectionType: 'about_me', config: { style: 'card' }, isVisible: true },
      { id: 'tpl-products', sectionType: 'all_products', config: { layout: 'grid', showFilters: true }, isVisible: true },
      { id: 'tpl-hours', sectionType: 'shop_hours', config: {}, isVisible: true },
      { id: 'tpl-pickup', sectionType: 'pickup_details', config: { showMap: false }, isVisible: true },
    ],
  },
  {
    id: 'midnight-luxe',
    name: 'Midnight Luxe',
    description: 'Dark, moody, upscale',
    vibe: 'Late-night confections',
    emoji: '🌙',
    colors: {
      primary: '#E8D5B7',
      secondary: '#B8997A',
      accent: '#D4AF37',
      background: '#1C1917',
      surface: '#292524',
      text: '#E7E5E4',
      textMuted: '#A8A29E',
      heading: '#FAFAF9',
      border: '#44403C',
    },
    fonts: { heading: 'DM Serif Display', body: 'DM Sans' },
    cardStyle: { variant: 'glass', border: 'none', iconStyle: 'outline' },
    heroSettings: { style: 'image', height: 'large', overlayOpacity: 0.5 },
    gradients: {
      hero: 'linear-gradient(135deg, #1C1917 0%, #44403C 100%)',
      accent: 'linear-gradient(135deg, #D4AF37 0%, #E8D5B7 100%)',
      card: 'linear-gradient(135deg, #292524 0%, #1C1917 100%)',
    },
    sections: [
      { id: 'tpl-hero', sectionType: 'hero', config: { height: 'large', showTagline: true, showCTA: true }, isVisible: true },
      { id: 'tpl-featured', sectionType: 'featured_products', config: { count: 3, style: 'card' }, isVisible: true },
      { id: 'tpl-divider', sectionType: 'divider', config: { style: 'line' }, isVisible: true },
      { id: 'tpl-products', sectionType: 'all_products', config: { layout: 'grid', showFilters: true }, isVisible: true },
      { id: 'tpl-about', sectionType: 'about_me', config: { style: 'card' }, isVisible: true },
      { id: 'tpl-reviews', sectionType: 'reviews', config: { count: 3, style: 'carousel' }, isVisible: true },
      { id: 'tpl-hours', sectionType: 'shop_hours', config: {}, isVisible: true },
      { id: 'tpl-pickup', sectionType: 'pickup_details', config: { showMap: false }, isVisible: true },
    ],
  },
  {
    id: 'garden-fresh',
    name: 'Garden Fresh',
    description: 'Bright greens, organic, natural',
    vibe: 'Straight from the garden',
    emoji: '🌿',
    colors: {
      primary: '#2D6A4F',
      secondary: '#52B788',
      accent: '#95D5B2',
      background: '#F0FFF4',
      surface: '#FFFFFF',
      text: '#1B4332',
      textMuted: '#588C73',
      heading: '#1B4332',
      border: '#B7E4C7',
    },
    fonts: { heading: 'Outfit', body: 'Open Sans' },
    cardStyle: { variant: 'white', border: 'primary', iconStyle: 'solid' },
    heroSettings: { style: 'image', height: 'medium', overlayOpacity: 0.2 },
    gradients: {
      hero: 'linear-gradient(135deg, #2D6A4F 0%, #52B788 100%)',
      accent: 'linear-gradient(135deg, #52B788 0%, #95D5B2 100%)',
      card: 'linear-gradient(135deg, #F0FFF4 0%, #D8F3DC 100%)',
    },
    sections: [
      { id: 'tpl-hero', sectionType: 'hero', config: { height: 'medium', showTagline: true, showCTA: true }, isVisible: true },
      { id: 'tpl-featured', sectionType: 'featured_products', config: { count: 4, style: 'card' }, isVisible: true },
      { id: 'tpl-categories', sectionType: 'product_categories', config: { showCounts: true }, isVisible: true },
      { id: 'tpl-products', sectionType: 'all_products', config: { layout: 'grid', showFilters: true }, isVisible: true },
      { id: 'tpl-newsletter', sectionType: 'newsletter_signup', config: { headline: 'Fresh picks weekly', description: 'Get notified when new seasonal products drop', buttonText: 'Subscribe' }, isVisible: true },
      { id: 'tpl-about', sectionType: 'about_me', config: { style: 'card' }, isVisible: true },
      { id: 'tpl-pickup', sectionType: 'pickup_details', config: { showMap: false }, isVisible: true },
      { id: 'tpl-hours', sectionType: 'shop_hours', config: {}, isVisible: true },
    ],
  },
  {
    id: 'hot-sauce-heat',
    name: 'Hot Sauce Heat',
    description: 'Fiery, bold, daring',
    vibe: 'Bring the heat',
    emoji: '🌶️',
    colors: {
      primary: '#DC2626',
      secondary: '#EA580C',
      accent: '#FBBF24',
      background: '#FEF9EF',
      surface: '#FFFFFF',
      text: '#451A03',
      textMuted: '#92400E',
      heading: '#7C2D12',
      border: '#FED7AA',
    },
    fonts: { heading: 'Oswald', body: 'Roboto' },
    cardStyle: { variant: 'white', border: 'accent', iconStyle: 'solid' },
    heroSettings: { style: 'gradient', height: 'medium', overlayOpacity: 0 },
    gradients: {
      hero: 'linear-gradient(135deg, #DC2626 0%, #EA580C 50%, #FBBF24 100%)',
      accent: 'linear-gradient(135deg, #EA580C 0%, #FBBF24 100%)',
      card: 'linear-gradient(135deg, #FEF9EF 0%, #FEF3C7 100%)',
    },
    sections: [
      { id: 'tpl-hero', sectionType: 'hero', config: { height: 'medium', showTagline: true, showCTA: true }, isVisible: true },
      { id: 'tpl-featured', sectionType: 'featured_products', config: { count: 3, style: 'card' }, isVisible: true },
      { id: 'tpl-products', sectionType: 'all_products', config: { layout: 'grid', showFilters: true }, isVisible: true },
      { id: 'tpl-reviews', sectionType: 'reviews', config: { count: 3, style: 'carousel' }, isVisible: true },
      { id: 'tpl-faq', sectionType: 'faq', config: { items: [{ q: 'How hot are your sauces?', a: 'We rate every bottle on our heat scale from 1 (mild) to 5 (inferno). Check each product page!' }, { q: 'Do you ship?', a: 'Currently pickup only, but shipping is coming soon!' }] }, isVisible: true },
      { id: 'tpl-about', sectionType: 'about_me', config: { style: 'card' }, isVisible: true },
      { id: 'tpl-pickup', sectionType: 'pickup_details', config: { showMap: false }, isVisible: true },
    ],
  },
  {
    id: 'lavender-fields',
    name: 'Lavender Fields',
    description: 'Soft, calming, pastoral',
    vibe: 'Peaceful countryside charm',
    emoji: '💜',
    colors: {
      primary: '#7C3AED',
      secondary: '#A78BFA',
      accent: '#C084FC',
      background: '#FAF5FF',
      surface: '#FFFFFF',
      text: '#3B0764',
      textMuted: '#7E5BAD',
      heading: '#581C87',
      border: '#E9D5FF',
    },
    fonts: { heading: 'Playfair Display', body: 'Poppins' },
    cardStyle: { variant: 'tinted', border: 'none', iconStyle: 'pill' },
    heroSettings: { style: 'image', height: 'large', overlayOpacity: 0.35 },
    gradients: {
      hero: 'linear-gradient(135deg, #7C3AED 0%, #C084FC 100%)',
      accent: 'linear-gradient(135deg, #A78BFA 0%, #C084FC 100%)',
      card: 'linear-gradient(135deg, #FAF5FF 0%, #F3E8FF 100%)',
    },
    sections: [
      { id: 'tpl-hero', sectionType: 'hero', config: { height: 'large', showTagline: true, showCTA: true }, isVisible: true },
      { id: 'tpl-about', sectionType: 'about_me', config: { style: 'card' }, isVisible: true },
      { id: 'tpl-featured', sectionType: 'featured_products', config: { count: 3, style: 'card' }, isVisible: true },
      { id: 'tpl-products', sectionType: 'all_products', config: { layout: 'grid', showFilters: true }, isVisible: true },
      { id: 'tpl-newsletter', sectionType: 'newsletter_signup', config: { headline: 'From our kitchen to yours', description: 'Subscribe for seasonal recipes and new product alerts', buttonText: 'Join us' }, isVisible: true },
      { id: 'tpl-reviews', sectionType: 'reviews', config: { count: 3, style: 'carousel' }, isVisible: true },
      { id: 'tpl-hours', sectionType: 'shop_hours', config: {}, isVisible: true },
      { id: 'tpl-pickup', sectionType: 'pickup_details', config: { showMap: false }, isVisible: true },
    ],
  },
  {
    id: 'coastal-catch',
    name: 'Coastal Catch',
    description: 'Ocean blues, breezy, fresh',
    vibe: 'Seaside market vibes',
    emoji: '🐚',
    colors: {
      primary: '#0369A1',
      secondary: '#0EA5E9',
      accent: '#F97316',
      background: '#F0F9FF',
      surface: '#FFFFFF',
      text: '#0C4A6E',
      textMuted: '#7DD3FC',
      heading: '#082F49',
      border: '#BAE6FD',
    },
    fonts: { heading: 'Space Grotesk', body: 'Inter' },
    cardStyle: { variant: 'white', border: 'primary', iconStyle: 'outline' },
    heroSettings: { style: 'image', height: 'medium', overlayOpacity: 0.25 },
    gradients: {
      hero: 'linear-gradient(135deg, #0369A1 0%, #0EA5E9 100%)',
      accent: 'linear-gradient(135deg, #F97316 0%, #FB923C 100%)',
      card: 'linear-gradient(135deg, #F0F9FF 0%, #E0F2FE 100%)',
    },
    sections: [
      { id: 'tpl-hero', sectionType: 'hero', config: { height: 'medium', showTagline: true, showCTA: true }, isVisible: true },
      { id: 'tpl-featured', sectionType: 'featured_products', config: { count: 3, style: 'card' }, isVisible: true },
      { id: 'tpl-products', sectionType: 'all_products', config: { layout: 'grid', showFilters: true }, isVisible: true },
      { id: 'tpl-about', sectionType: 'about_me', config: { style: 'card' }, isVisible: true },
      { id: 'tpl-reviews', sectionType: 'reviews', config: { count: 3, style: 'carousel' }, isVisible: true },
      { id: 'tpl-pickup', sectionType: 'pickup_details', config: { showMap: false }, isVisible: true },
      { id: 'tpl-hours', sectionType: 'shop_hours', config: {}, isVisible: true },
    ],
  },
]
